name: DECEIT CONCEPT ART
favicon: null
layout_spectrum: 0.11861
typography_spectrum: 0.3041
title: DECEIT
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#20180d'
    - '#335149'
    - '#729c8e'
    - '#fefefe'
    - '#dfd2be'
  brandStrength: 0
  lightness: 0.08028290257789195
  saturation: 0.6551278126426041
  rhythmicContrast: 0.5
purpose: []
